[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "chromium"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --prefer-offline"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
